baseURL = 'https://alexandrahollins.github.io/content/'
languageCode = 'en-us'
title = 'Alexandra Hollins'
theme = 'PaperMod'

[params]
  author = "Christopher Hart"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ChristopherJHart"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"