baseURL = 'https://alexandra.hollins.io/'
languageCode = 'en-us'
title = 'Alexandra Hollins'
theme = "m10c"

[taxonomies]
   tag = "tags"

[params]
  author = "Alexandra"
  description = "I am working with #PowerBi #PowerApps #PowerPlatform"
  avatar = "avatar profile photo.png"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/alexandrahollins"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIN"
    url = "https://www.linkedin.com/in/alexandrahollins/"

      # Default theme
  [params.style]
   darkestColor = "#ffffff"
   darkColor = "#ffffff"
   lightColor = "#000000"
   lightestColor = "#15181C"
   primaryColor = "#000080"